[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"
  environment = { SECRETS_SCAN_OMIT_PATHS = "README.md,js/config.js,js/utils.js,dist/js/config.js,dist/js/utils.js" }

[dev]
  command = "npm run dev"
  port = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
